name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  call-nodejs-ci:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node-version: '18'

  test:
    runs-on: ubuntu-latest
    needs: call-nodejs-ci
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    env:
      MONGO_URI: mongodb://localhost:27017/cartdb
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB..."
          for i in {1..20}; do
            nc -z localhost 27017 && echo "MongoDB is up" && break
            sleep 2
          done
      - name: Start server
        run: nohup node src/server.js > server.log 2>&1 &
      - name: Run tests
        run: node ./test-cart.js
      
  build-push-dockerapp:
    runs-on: ubuntu-latest
    needs:
      - call-nodejs-ci
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Docker Login 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }} 
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            yousef2005/cart-service:latest
            yousef2005/cart-service:${{ github.sha }}
            yousef2005/cart-service:1.0.${{ github.run_number }}
